### ISSUE TITLE
Reference implementation of task execution APIs using Azure ML

### ISSUE THREAD

**Issue by dkmiller** [Azure-Samples/azure-ml-federated-learning#12]
What we'd implement: http://ga4gh.github.io/task-execution-schemas/

How? Fully stateless Azure function which does schema translations + Azure ML workspace

Stretch: use Azure ML pipelines to orchestration the federated side of things, could be an alternative approach to [Cromwell](https://github.com/microsoft/CromwellOnAzure) + [Terra WDL](https://support.terra.bio/hc/en-us/articles/360037132732-task)

**Comment by thomasp-ms** [comment]
First prototype was introduced [here](https://github.com/Azure-Samples/azure-ml-federated-learning/tree/main/tes-api-on-azure-ml)a few months back, and was communicated to customers.

We are now about to clean up the repository, and will remove this part since there was little interest. Code will remain available in the repo history though.
